### ISSUE TITLE
Index out of bounds exception

### ISSUE THREAD

**Issue by muldvarp** [tcsprojects/pgsolver#22]
The game (after transformed into a max-parity game)

`parity 8;
0 2 0 1,4 "v0";
1 3 1 0,2 "v1";
2 1 0 3,6 "v2";
3 0 1 1,3 "v3";
4 4 1 5,6 "v4";
5 1 1 4,6 "v5";
6 4 0 5,7 "v6";
7 2 0 4 "v7";`

induces an index-out-of-bounds-exception:

`eigheach [~/ownCloud/projects/pgsolver] bin/transformer -mm test.gm | bin/pgsolver -global recursive -v 3
PGSolver Collection Ver. 4.0: Parity Game Solver
Authors: Oliver Friedmann (University of Munich) and Martin Lange (University of Kassel), 2008-2017
http://tcsprojects.org

Reading game from ..................... STDIN
Parsing ............................... 0.00 sec
Chosen solver `recursive' ............. 
[MAIN: 1.57 msec]  Starting Universal Solving Process
[MAIN: 0.04 msec]  Considering game...
[MAIN: 0.01 msec]    Nodes = 8
[MAIN: 0.01 msec]    Edges = 15
[MAIN: 0.01 msec]    Index = 5
[GLOBAL: 0.03 msec]  Entering global preprocessing phase...
[GLOBAL: 0.01 msec]  Removing useless self cycles... 1 transition(s) removed!
[GLOBAL: 0.04 msec]  Created sinks: 0!
[GLOBAL: 0.03 msec]  Searching for useful self cycles... 0 node(s) found!
  [DECOMP: 0.21 msec]  Entering decomposition phase at recursion level 0
  [DECOMP: 0.04 msec]  Considering game of size 8
  [DECOMP: 0.06 msec]  Decomposed game into 2 SCCs, size of largest SCC is 4
  [DECOMP: 0.03 msec]  Entering SCC #1 of size 4
  [LOCAL: 0.04 msec]  Reducing index 4 down to... 2!
    [BACKEND: 0.05 msec]  Calling backend for this SCC...
    [RECURSIVE: 0.02 msec]  Solving the game: [0:0,1,{1,2};1:1,1,{0,2};2:0,0,{1,3};3:0,0,{0}]
    [RECURSIVE: 0.03 msec]  Highest priority 1 belongs to player 1
    [RECURSIVE: 0.01 msec]  The following nodes have priority 1: P = {1}
    [RECURSIVE: 0.02 msec]  The attractor of P for player 1 is: {0,1,2,3}
    [RECURSIVE: 0.01 msec]  First recursive descent to subgame ...

    [MAIN: 0.02 msec]  Starting Universal Solving Process
    [MAIN: 0.01 msec]  Considering game...
    [MAIN: 0.01 msec]    Nodes = 0
    [MAIN: 0.01 msec]    Edges = 0
Fatal error: exception Invalid_argument("index out of bounds")
`

**Comment by oliverfriedmann** [comment]
Should be fine now - can you try?
