### ISSUE TITLE
Basics.message_depth_tagged - is there any reason why last_time is always saved?

### ISSUE THREAD

**Issue by Lammatian** [tcsprojects/pgsolver#25]
As far as I understand it, `message_depth_tagged` updates the `last_time` variable every time it is called. Is there any reason why `last_time` is updated even if the actual message is not being output?

This affects the runtime heavily - even if the logs are not displayed, the lines
`let now = Sys.time () in`
and
`last_time := now`
are always being called. If this is not done on purpose, a suggested fix would be to just put both of the lines mentioned above in the inline function, resulting in something like

```
let message_depth_tagged u depth tag s =
  message_depth u depth (fun x -> 
    let now = Sys.time() in
    let last_time_ = !last_time in
    last_time := now;
    "[" ^ String.capitalize_ascii (tag x) ^ ": " ^ Printf.sprintf "%.2f msec" (1000.0 *. (Sys.time() -. last_time_)) ^ "]  " ^ s x)
```

**Comment by oliverfriedmann** [comment]
You are absolutely right. Happy to pull in a PR for this.
