### ISSUE TITLE
Missing citation information

### ISSUE THREAD

**Issue by aweinert** [tcsprojects/pgsolver#29]
I cannot find any information on how to properly cite `pgsolver` when using it for a publication in the repository. Also, there does not appear to be any release of `pgsolver` on [zenodo](https://zenodo.org/), which would assign it a citable DOI.

It would be great if you could indicate a preferred citation for `pgsolver` either in the `README.md` or using a [CITATION.cff](https://github.com/citation-file-format/citation-file-format) file in the root of the repository. Otherwise, I would greatly appreciate any information on how to properly cite this software.

**Comment by muldvarp** [comment]
Thanks for pointing this out! I will look into adding the info to the files directly. Meanwhile, the best way to cite PGSolver is via

O. Friedmann, M. Lange. Solving Parity Games in Practice. In Proc. of the 7th Int. Symp. on Automated Technology for Verification and Analysis, ATVA'09, Macao, China, 2009 volume 5799 of Lecture Notes in Computer Science, pages 182-196, Springer, 2009

The DOI is 10.1007/978-3-642-04761-9_15 .

**Comment by aweinert** [comment]
Thanks for the info. Is that reference also the one you want people to cite in the long-term if they reference PGSolver? If so, I'd be happy to add a pull request adding such a file :)

**Comment by oliverfriedmann** [comment]
apologies for the delay - yes please, a PR for this would be fantastic!
