### ISSUE TITLE
Issue with OCaml 4.13.1

### ISSUE THREAD

**Issue by valvestate** [tcsprojects/pgsolver#31]
Hi, I have got the following issue using OCaml 4.13.1

`File "src/solvers/satsolve.ml", line 29, characters 6-12:
29 |                                            solver#add_helper_exactlyone 0 (Array.length delta - 1) [||] (fun j -> Po (Strategy (i, delta.(j))))) game;
           ^^^^^^
Error: This expression has type
         Timing.timetable option -> 'weak2 Satwrapper.satWrapper
       It has no method add_helper_exactlyone
Command exited with code 2.`

Any fixes for this issue? Thanks!

**Comment by oliverfriedmann** [comment]
should be fixed - was an issue not with OCaml 4.13.1 but with the SATSolversForOcaml dependency
