### ISSUE TITLE
Problem with compiling on Windows

### ISSUE THREAD

**Issue by FerryT** [tcsprojects/pgsolver#4]
This problem is possibly caused by changes in OCaml but currently `make` will fail on Windows (not sure if this is the case for everyone but it is for me on a fresh install).
It spews out a couple of link errors: `undefined reference to 'flexdll_dlopen'` etc.

The problem is related to this: http://caml.inria.fr/mantis/print_bug_page.php?bug_id=4784

As suggested I removed the compiler flag (line 52 in the Makefile from `CPPCOMPILER=-cc $(OCAMLOPTCPP)` to `CPPCOMPILER=`) and this completely solves the problem.

I don't know if this breaks the makefile on other platforms so I though I just let it know.

Thanks for your time.

**Comment by oliverfriedmann** [comment]
Thanks, will look into it.

**Comment by oliverfriedmann** [comment]
Removing the flag doesn't seem to break for the newest versions of Mac OS-X and Debian Wheezy, so fingers crossed.

**Comment by FerryT** [comment]
Thanks, works like a charm now!
