### ISSUE TITLE
Problem compiling (on OS X)

### ISSUE THREAD

**Issue by jkeiren** [tcsprojects/pgsolver#5]
Commit 72a22651379d75d98f024f25508ad4ab08a20ffb fails to compile for me (running OS X). The relevant snippet of the output is the following:

```
ocamlopt -I src -I obj -I /usr/local/lib/ocaml -I ./satsolversforocaml/obj -I ./tcslib/obj -I   /usr/local/lib/z3/ocaml -c -o obj/switch_zadeh.cmx src/solvers/stratimpralgs/switch_zadeh.ml
File "src/solvers/stratimpralgs/switch_zadeh.ml", line 17, characters 55-66:
Error: Unbound module Bits
make: *** [obj/switch_zadeh.cmx] Error 2
```

It seems that Bits is not included anywhere, but it is used in the Zadeh approach to strategy improvement. As a workaround, commenting the line `$(PGSOLVERSOBJ)/switch_zadeh.$(COMPILEEXT) \` in the file `SolverList` disables this particular solver, but allows you to compile and run the tools with the other solvers enabled.

**Comment by oliverfriedmann** [comment]
Have you tried git submodule update ?

**Comment by jkeiren** [comment]
Thanks Oliver, for the quick reply. That indeed seems to have been the issue. Sorry for missing that step.
